### PR TITLE
Python 3 compatibility & Django > 1.4 compatibility for tests.

### PR DESCRIPTION
**Pull request by mitchellrj**
All very straightforward and will not break old versions. All tests passing.

### CODE REVIEW

**Comment by mitchellrj** [comment]
Yo, @chrisglass.

**Comment by chrisglass** [comment]
Nice, thanks!

**Comment by mitchellrj** [comment]
Any chance of a fresh release to PyPI?

**Comment by chrisglass** [comment]
Hmmm maybe, I haven't done that in ages, so I'll have to dust that off. And my time is kind of limited these days, but I'll do what I can.

**Comment by chrisglass** [comment]
Ok, that's done. Turns out it wasn't so dusty after all, and TIL twine.

Donations welcome :) 1Dbaej2G7n46Tp4GsnMqKeY5vTXtzzLT73

**Pull request merged**
